ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    publish_tf: true
    publish_acceleration: false

    # IMU parameters
    imu0: '/imu/data'
    imu0_config: [false, false, false,
                  true, true, true,
                  false, false, false,
                  true, true, true,
                  false, false, false]
    imu0_differential: false
    imu0_relative: true

    # Odometry parameters
    odom0: '/odom'
    odom0_config: [true, true, true,
                   false, false, true,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    odom0_differential: false
    odom0_relative: false

    # Process noise covariance
    process_noise_covariance: [0.05, 0, 0, 0, 0, 0,
                               0, 0.05, 0, 0, 0, 0,
                               0, 0, 0.05, 0, 0, 0,
                               0, 0, 0, 0.01, 0, 0,
                               0, 0, 0, 0, 0.01, 0,
                               0, 0, 0, 0, 0, 0.01]

    # Initial estimate of the state
    initial_estimate_covariance: [1e-9, 0, 0, 0, 0, 0,
                                  0, 1e-9, 0, 0, 0, 0,
                                  0, 0, 1e-9, 0, 0, 0,
                                  0, 0, 0, 1e-9, 0, 0,
                                  0, 0, 0, 0, 1e-9, 0,
                                  0, 0, 0, 0, 0, 1e-9]

    # Control input parameters
    use_control: false
    stamped_control: false
    control_timeout: 0.2
    control_config: [true, true, false, false, false, false]

    # State estimate publication parameters
    map_frame: 'map'
    odom_frame: 'odom'
    base_link_frame: 'base_link'
    world_frame: 'odom'
